import type { Metadata } from "next"
// import localFont from "next/font/local"
import "./globals.css"
import { ThemeAppProvider } from "@/presentation/providers/ThemeProvider"
import { Toaster } from "@/presentation/ds/toaster"
import { ClientCacheProvider } from "@/presentation/providers/ClientCacheProvider"
import { AppProvider } from "@/presentation/providers/AppProvider"
import { Roboto } from 'next/font/google'

// const geistSans = localFont({
//   src: "../../presentation/assets/fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// })

// const geistMono = localFont({
//   src: "../../presentation/assets/fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// })

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap', // Mejora la renderización
  variable: '--font-roboto', // Opcional: para usarla como variable CSS
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  params: { lang },
  children,
}: Readonly<{
  children: React.ReactNode
  params: { lang: 'es'| 'en' }
}>) {
  return (
    <html lang={lang} className={roboto.variable}>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className='antialiased'
      >
        <ClientCacheProvider>
          <AppProvider>
            <ThemeAppProvider>
              {children}
              <Toaster />
            </ThemeAppProvider>
          </AppProvider>
        </ClientCacheProvider>
      </body>
    </html>
  )
}
