import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeAppProvider } from "@/presentation/providers/ThemeProvider";
import { Toaster } from "@/presentation/ui/molecules/toaster";

const geistSans = localFont({
  src: "../../presentation/assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../../presentation/assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  params: { lang },
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: any }
}>) {
  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeAppProvider>
          {children}
          <Toaster />
        </ThemeAppProvider>
      </body>
    </html>
  );
}
